apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc-deployment
  labels:
    app: auth-svc-lbl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-svc-lbl
  template:
    metadata:
      labels:
        app: auth-svc-lbl
    spec:
      serviceAccountName: acc-svc-sa
      initContainers:
        - name: wait-for-database-migration-job
          image: groundnuty/k8s-wait-for:v2.0
          args:
            - "job"
            - "auth-db-migrator"
      containers:
        - name: auth-svc
          image: dergunnik/streaming-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DbCredentials__User
              valueFrom:
                secretKeyRef:
                  name: auth-pgsql-secret
                  key: pgsql-user
            - name: DbCredentials__Password
              valueFrom:
                secretKeyRef:
                  name: auth-pgsql-secret
                  key: pgsql-password
            - name: DbCredentials__Db
              valueFrom:
                secretKeyRef:
                  name: auth-pgsql-secret
                  key: pgsql-db
            - name: DbCredentials__Host
              valueFrom:
                configMapKeyRef:
                  name: auth-pgsql-config
                  key: db-url
            - name: DbCredentials__Port
              valueFrom:
                configMapKeyRef:
                  name: auth-pgsql-config
                  key: db-port
            - name: JwtSettings__Key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-key
            - name: JwtSettings__Issuer
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: issuer
            - name: JwtSettings__Audience
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: audience
            - name: EmailServiceAddress__Host
              valueFrom:
                configMapKeyRef:
                  name: email-service-config
                  key: host
            - name: EmailServiceAddress__Port
              valueFrom:
                configMapKeyRef:
                  name: email-service-config
                  key: port
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth-svc-lbl
  ports:
    - name: grpc-and-http
      protocol: TCP
      port: 8080
      targetPort: 8080
