apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-lbl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-lbl
  template:
    metadata:
      labels:
        app: gateway-lbl
    spec:
      containers:
        - name: gateway
          image: dergunnik/streaming-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: JwtSettings__Key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-key
            - name: JwtSettings__Issuer
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: issuer
            - name: JwtSettings__Audience
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: audience
            - name: ServiceAddresses__AuthService__Host
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: host
            - name: ServiceAddresses__AuthService__Port
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: port
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-lbl
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      