apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-svc-deployment
  labels:
    app: live-svc-lbl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: live-svc-lbl
  template:
    metadata:
      labels:
        app: live-svc-lbl
    spec:
      containers:
        - name: live-svc
          image: dergunnik/streaming-live-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DbCredentials__User
              valueFrom:
                secretKeyRef:
                  name: live-pgsql-secret
                  key: pgsql-user
            - name: DbCredentials__Password
              valueFrom:
                secretKeyRef:
                  name: live-pgsql-secret
                  key: pgsql-password
            - name: DbCredentials__Db
              valueFrom:
                secretKeyRef:
                  name: live-pgsql-secret
                  key: pgsql-db
            - name: DbCredentials__Host
              valueFrom:
                configMapKeyRef:
                  name: live-pgsql-config
                  key: db-url
            - name: DbCredentials__Port
              valueFrom:
                configMapKeyRef:
                  name: live-pgsql-config
                  key: db-port
            - name: CloudinarySettings__CloudName
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: cloud-name
            - name: CloudinarySettings__ApiKey
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-key
            - name: CloudinarySettings__ApiSecret
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-secret
            - name: ConnectionStrings__RedisSignalRBackplane
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: connection-string
            - name: JwtSettings__Key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-key
            - name: JwtSettings__Issuer
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: issuer
            - name: JwtSettings__Audience
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: audience
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: live-svc
spec:
  selector:
    app: live-svc-lbl
  ports:
    - name: grpc-and-http
      protocol: TCP
      port: 8080
      targetPort: 8080
