apiVersion: batch/v1
kind: Job
metadata:
  name: acc-db-migrator
spec:
#  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: acc-db-migrator
    spec:
      restartPolicy: OnFailure
      containers:
        - name: acc-db-migrator-container
          image: dergunnik/streaming-account-service-migrator:latest
          env:
            - name: DbCredentials__User
              valueFrom:
                secretKeyRef:
                  name: acc-pgsql-secret
                  key: pgsql-user
            - name: DbCredentials__Password
              valueFrom:
                secretKeyRef:
                  name: acc-pgsql-secret
                  key: pgsql-password
            - name: DbCredentials__Db
              valueFrom:
                secretKeyRef:
                  name: acc-pgsql-secret
                  key: pgsql-db
            - name: DbCredentials__Host
              valueFrom:
                configMapKeyRef:
                  name: acc-pgsql-config
                  key: db-url
            - name: DbCredentials__Port
              valueFrom:
                configMapKeyRef:
                  name: acc-pgsql-config
                  key: db-port
            - name: CloudinarySettings__ApiKey
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-key
            - name: CloudinarySettings__ApiSecret
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-secret
            - name: JwtSettings__Key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-key
            - name: JwtSettings__Issuer
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: issuer
            - name: JwtSettings__Audience
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: audience