apiVersion: v1
kind: ServiceAccount
metadata:
  name: acc-svc-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acc-svc-sa-jobs-binding
subjects:
  - kind: ServiceAccount
    name: acc-svc-sa
roleRef:
  kind: ClusterRole
  name: job-reader-permission
  apiGroup: rbac.authorization.k8s.io
  