apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-svc-deployment
  labels:
    app: email-svc-lbl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-svc-lbl
  template:
    metadata:
      labels:
        app: email-svc-lbl
    spec:
      containers:
        - name: email-svc
          image: dergunnik/streaming-email-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 5000
          env:
            - name: EmailCredentials__Email
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email
            - name: EmailCredentials__AppPassword
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: app-password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: email-svc-service
spec:
  selector:
    app: email-svc-lbl
  ports:
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
      