apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vod-pgsql
  labels:
    app: vod-pgsql-lbl
spec:
  serviceName: vod-pgsql-service
  replicas: 1
  selector:
    matchLabels:
      app: vod-pgsql-lbl
  template:
    metadata:
      labels:
        app: vod-pgsql-lbl
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: vod-pgsql-container
          image: postgres:16
          ports:
            - name: pgsql
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vod-pgsql-secret
                  key: pgsql-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vod-pgsql-secret
                  key: pgsql-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: vod-pgsql-secret
                  key: pgsql-db
            - name: PGDATA 
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgsql-data
              mountPath: /var/lib/postgresql/data 
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "$(POSTGRES_USER)"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "$(POSTGRES_USER)"
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: pgsql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: vod-pgsql-service
  labels:
    app: vod-pgsql-lbl
spec:
  selector:
    app: vod-pgsql-lbl
  ports:
    - name: pgsql
      protocol: TCP
      port: 5432
      targetPort: 5432 
