apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-pgsql-deployment
  labels:
    app: vod-pgsql-lbl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vod-pgsql-lbl
  template:
    metadata:
      labels:
        app: vod-pgsql-lbl
    spec:
      containers:
        - name: vod-pgsql
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: vod-pgsql-secret
                  key: pgsql-user
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: vod-pgsql-secret
                  key: pgsql-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: vod-pgsql-secret
                  key: pgsql-db
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "$(POSTGRES_USER)"
                - -d
                - "$(POSTGRES_DB)"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "$(POSTGRES_USER)"
                - -d
                - "$(POSTGRES_DB)"
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: vod-pgsql-service
spec:
  selector:
    app: vod-pgsql-lbl
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
